name: Test Updating Version

# run-name: Test Updating Version ${{ inputs.workspace_distribution }}

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_PUSH }}
          # - bumpalicious-test-github-push — repo
          fetch-depth: 0 # Required if you’ll push to an existing branch

      - name: Provision Code
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "This is a test project" > README.md
          echo '{ "version": "0.0.1", "name": "single-project" }' > package.json
          mkdir workspaces1
          echo "This is a workspaces project 1" > workspaces1/README.md
          echo '{ "version": "0.0.5", "name": "@main-workspace/workspace1" }' > workspaces1/package.json
          mkdir workspaces2
          echo "This is a workspaces project 2" > workspaces2/README.md
          echo '{ "version": "0.0.31", "name": "@main-workspace/workspace2" }' > workspaces2/package.json

          git add -A
          git diff-index --quiet HEAD || git commit -m "chore: auto-update [skip ci]"
          git push

          git tag v0.0.1
          git push origin v0.0.1

  cleanup:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - prerequisites
    steps:
      - name: Checkout repo
        if: ${{ always() }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_PUSH }}
          fetch-depth: 0 # Required if you’ll push to an existing branch

      - name: Clean Repo
        if: ${{ always() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          rm -rf workspaces* package.json README.md

          git add -A
          git diff-index --quiet HEAD || git commit -m "chore: auto-update [skip ci]"

          git push

          git pull

          git push --delete origin v0.0.1

  # test-update-version::
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       workspace_distribution:
  #         - single
  #         - single-with-pr
  #         - workspaces
  #         - workspaces-with-pr
  #       token_type:
  #         - tap
  #         - app
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #
  #     - name: Create Single Project Repo
  #       if: ${{ contains(inputs.workspace_distribution, 'single') }}
  #       run: |
  #         echo "This is a test project" > README.md
  #         echo "This is a test project" > index.js
  #         echo '{ "version": "0.0.1", "name": "single-project" }' > package.json
  #

  #
  #     - name: Providion Git Version
  #       run: |
  #         git config --global user.name "git.user[bot]"
  #         git config --global user.email "git.user[bot]@github.com"
  #
  #         # TODO: remove all existing tags from the repo

  # - name: Update Repo Version (by Commit)
  #   if: ${{ inputs.workspace_distribution == 'single' }}
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GH_BUMPALICIOUS_TOKEN }}
  #   uses: dragoscops/bumpalicious@2_0_node
  #   with:
  #     workspaces: ".:text"
  #
  # - name: Update Repo Version (by Pull Request)
  #   if: ${{ inputs.workspace_distribution == 'single-with-pr' }}
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GH_BUMPALICIOUS_TOKEN }}
  #   uses: dragoscops/bumpalicious@2_0_node
  #   with:
  #     workspaces: ".:text"
  #     pr: "true"
  #     pr_auto_merge: "true"
  #
  # - name: Update Workspaces Version (by Commit)
  #   if: ${{ inputs.workspace_distribution == 'workspaces' }}
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GH_BUMPALICIOUS_TOKEN }}
  #   uses: dragoscops/bumpalicious@2_0_node
  #   with:
  #     workspaces: ".:text,${{steps.workspaces3.outputs.workspaces_projects}}"
  #
  # - name: Update Workspaces Version (by Pull Request)
  #   if: ${{ inputs.workspace_distribution == 'workspaces-with-pr' }}
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GH_BUMPALICIOUS_TOKEN }}
  #   uses: dragoscops/bumpalicious@2_0_node
  #   with:
  #     workspaces: ".:text,${{steps.workspaces3.outputs.workspaces_projects}}"
  #     pr: "true"
  #     pr_auto_merge: "true"
