name: Test Updating Version

run-name: Test Updating Version ${{ inputs.workspace_distribution }}

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pr:
          - false
          - true
      max-parallel: 1
    steps:
      - name: Github App Token
        id: app-token-push
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_APP_PUSH_ID }}
          private-key: ${{ secrets.GH_APP_PUSH_KEY }}

      # PAT Settings:
      # - repo (full)
      # Github App:
      # - Content: read & write
      # - Pull Requests: read & write
      # - Administration: read

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token-push.outputs.token || secrets.GH_TOKEN_PUSH }}
          fetch-depth: 0 # Required if you’ll push to an existing branch

      # - name: Reconfigure Remote
      #   shell: bash
      #   run: |
      #     REMOTE_REPO="https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git"
      #     echo "Setting authenticated remote URL..."
      #     git remote set-url origin "$REMOTE_REPO"

      - name: Provision Code
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          set -ex

          git pull origin ${{ github.ref_name }}

          echo "This is a test project" > README.md
          echo '{ "version": "0.0.1", "name": "single-project" }' > package.json
          mkdir -p workspaces1
          echo "This is a workspaces project 1" > workspaces1/README.md
          echo '{ "version": "0.0.5", "name": "@main-workspace/workspace1" }' > workspaces1/package.json
          mkdir -p workspaces2
          echo "This is a workspaces project 2" > workspaces2/README.md
          echo '{ "version": "0.0.31", "name": "@main-workspace/workspace2" }' > workspaces2/package.json

          git add -A
          git diff-index --quiet HEAD || git commit -m "chore: auto-update [skip ci]"
          git push

          git tag v0.0.1
          git push origin v0.0.1

          git pull origin ${{ github.ref_name }}
          git tag -l

      - name: Providion Git Version
        run: |
          set -ex

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git pull origin ${{ github.ref_name }} --ff-only
          date > README.md
          date > workspaces1/README.md

          git status
          git diff

          git add -A
          git commit -am "fix: patch commit test"
          git pull origin ${{ github.ref_name }} --ff-only
          git push

      - name: Update Version
        uses: dragoscops/bumpalicious@prepare_release
        with:
          pr: ${{ matrix.pr }}
          pr_auto_merge: true
          token: ${{ steps.app-token-push.outputs.token || secrets.GH_TOKEN_PUSH }}
          workspaces: .:node

      - name: Validate Version Bump
        run: |
          set -ex

          git fetch

          git tag -l
          git branch -a

          git tag -l | grep v0.0.2

      - name: Clean Repo
        if: ${{ always() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          set -ex

          git pull origin ${{ github.ref_name }}
          git tag -l

          rm -rf workspaces* package.json README.md

          git add -A
          git diff-index --quiet HEAD || git commit -m "chore: auto-update [skip ci]"

          git push

          git pull origin ${{ github.ref_name }}

          git tag -l | xargs git push --delete origin
